### ISSUE TITLE
Microphone using

### ISSUE THREAD

**Issue by ndubkov** [picoxr/AndroidHelper#4]
Is there is any way to use microphone in Pico VR 2G 4K Headset?
I tried to use default way (with standard Android SDK) for AudioRecord initialization and I got error (attached screenshot)

![image](https://user-images.githubusercontent.com/2602322/99298607-05d65680-285b-11eb-9e87-9f95f34b640a.png)

Thank you

**Comment by picoxr** [comment]
The standard Android API is working on our devices.
Your issue may caused by permisson. Pls refer to the doc below to request ``android.permission.RECORD_AUDIO`` permission.
Unity: https://docs.unity3d.com/Manual/android-RequestingPermissions.html
Android: https://developer.android.com/training/permissions/requesting

**Comment by ndubkov** [comment]
Ok, I got it. 
I thought there is no need to request permissions via `requestPermissions` call, because there is no way to grant permission via Pico's app settings. It's just specifies a list of app's permissions

Anyway, after `requestPermissions` is works fine. 
Thank you!
